name: Sync Shared Files to Datapack Branches

on:
  push:
    branches:
      - main  # Runs when pushing to the "main" branch
  workflow_dispatch:  # Allows manual execution from GitHub

jobs:
  merge-main:
    name: Merge Main into Datapack Branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history is available

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch all branches and sync
        run: |
          # Ensure all branches are fetched
          git fetch --all
          
          # List all remote branches excluding 'main'
          BRANCHES=$(git branch -r | grep -Eo "origin/[^/]+" | sed 's/origin\///' | grep -vE '^(main)$')

          echo "Branches to merge from main: $BRANCHES"
          
          # Loop through each branch
          for branch in $BRANCHES; do
            echo "-------------------------------------"
            echo "Merging main into $branch..."

            # Checkout the branch
            git checkout "$branch"
            if [ $? -ne 0 ]; then
              echo "Error checking out branch: $branch"
              continue
            fi

            # Pull the latest changes for the branch
            git pull origin "$branch" --rebase  # Using rebase to avoid merge commits
            if [ $? -ne 0 ]; then
              echo "Error pulling from branch: $branch"
              continue
            fi

            # Merge the main branch into the current branch
            git merge --no-edit origin/main
            if [ $? -ne 0 ]; then
              echo "Merge conflict detected, skipping branch: $branch"
              continue
            fi

            # Push the updated branch back to origin
            git push origin "$branch"
            if [ $? -ne 0 ]; then
              echo "Error pushing branch: $branch"
              continue
            fi

            echo "Successfully merged main into $branch and pushed changes."
          done
